version: "3.8"

services:
  ss2023_wa_foodiemate_user_api:
    build: backend/user_api
    container_name: ss2023_wa_foodiemate_user_api
    restart: always
    ports:
      - 20063:20063
    depends_on:
      - ss2023_wa_foodiemate_database
    environment:
      - MONGO_URI=mongodb://ss2023_wa_foodiemate_database:20062/foodiemate


    networks:
      - ss2023_wa_foodiemate

  ss2023_wa_foodiemate_recipe_api:
    build: backend/recipe_api
    container_name: ss2023_wa_foodiemate_recipe_api
    restart: always
    ports:
      - 20064:20064
    depends_on:
      - ss2023_wa_foodiemate_database
    environment:
      - MONGO_URI=mongodb://ss2023_wa_foodiemate_database:20062/foodiemate


    networks:
      - ss2023_wa_foodiemate

  ss2023_wa_foodiemate_cooking_together_api:
    build: backend/cooking_together_api
    container_name: ss2023_wa_foodiemate_cooking_together_api
    restart: always
    ports:
      - 20065:20065
    depends_on:
      - ss2023_wa_foodiemate_database
    environment:
      - MONGO_URI=mongodb://ss2023_wa_foodiemate_database:20062/foodiemate


    networks:
      - ss2023_wa_foodiemate

  ss2023_wa_foodiemate_database:
    image: mongo:4.4
    container_name: ss2023_wa_foodiemate_database
    restart: always
    ports:
      - 20062:27017
    #command: mongod --logpath /var/log/mongodb/mongod.log --logappend --quiet --setParameter logLevel=2
    volumes:
      - ./database:/data/db
    networks:
      - ss2023_wa_foodiemate


  ss2023_wa_foodiemate_frontend:
    build: frontend
    container_name: ss2023_wa_foodiemate_frontend
    ports:
      - 20061:20061

    environment:
      - REACT_APP_IP_ADDR=194.94.204.27

    networks:
      - ss2023_wa_foodiemate

networks:
  ss2023_wa_foodiemate:
