version: "3.7"

services:
  backend:
    build: express_backend
    container_name: backend_ss2023_wa_foodiemate
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/example_db
    volumes:
      - ./express_backend:/usr/src/app

    networks:
      - private

  database:
    image: mongo:4.4.5
    container_name: database_ss2023_wa_foodiemate
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - private

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://database:27017/
    networks:
      - private


networks:
  private:
