version: "3.7"

services:
  user_api:
    build: user_api
    container_name: user_api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/example_db
    volumes:
      - ./user_api:/usr/src/app

    networks:
      - private

  recipe_api:
    build: recipe_api
    container_name: recipe_api
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/example_db
    volumes:
      - ./recipe_api:/usr/src/app

    networks:
      - private

  database:
    image: mongo:4.4.5
    container_name: database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - private

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://database:27017/
    networks:
      - private


networks:
  private:
