version: "3.8"

services:
  ss2023_wa_foodiemate_user_api:
    build: user_api
    container_name: user_api
    restart: always
    ports:
      - 20063:20063
    depends_on:
      - ss2023_wa_foodiemate_database
    environment:
      - MONGO_URI=mongodb://database:20062/foodiemate
    volumes:
      - ./user_api:/usr/src/app

    networks:
      - private

  ss2023_wa_foodiemate_recipe_api:
    build: recipe_api
    container_name: recipe_api
    restart: always
    ports:
      - 20064:20064
    depends_on:
      - ss2023_wa_foodiemate_database
    environment:
      - MONGO_URI=mongodb://database:20062/foodiemate
    volumes:
      - ./recipe_api:/usr/src/app

    networks:
      - private

  ss2023_wa_foodiemate_cooking_together_api:
    build: cooking_together_api
    container_name: cooking_together_api
    restart: always
    ports:
      - 20065:20065
    depends_on:
      - ss2023_wa_foodiemate_database
    environment:
      - MONGO_URI=mongodb://database:20062/foodiemate
    volumes:
      - ./cooking_together_api:/usr/src/app

    networks:
      - private

  ss2023_wa_foodiemate_database:
    image: mongo:4.4.5
    container_name: database
    restart: always
    ports:
      - 20062:27017
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend --quiet --setParameter logLevel=2
    volumes:
      - ./data:/data/db
    networks:
      - private

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://database:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=adminHL
      - ME_CONFIG_BASICAUTH_PASSWORD=passHL
    networks:
      - private
    depends_on:
      - ss2023_wa_foodiemate_database

  ss2023_wa_foodiemate_frontend:
    build: frontend
    container_name: frontend
    ports:
      - 20061:3000
    volumes:
      - ./frontend:/app
    networks:
      - private

networks:
  private:
