components:
  schemas:
    Recipe:
      type: object
      properties:
        title:
          type: string
          description: Titel des Rezepts
        ingredients:
          type: array
          items:
            type: string
          description: Liste der Zutaten
        instructions:
          type: string
          description: Zubereitungsanweisungen des Rezepts
        image:
          type: string
          description: Bild des Rezepts
        drink:
          type: string
          description: Getränk des Rezepts

paths:
  /:
    get:
      summary: Recipe entry endpoint
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /new/:
    post:
      summary: Create a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '500':
          description: Server Error
          content:
            application/json:

  /allRecipes:
    get:
      summary: Get all recipes
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '500':
          description: Internal Server Error
          content:
            application/json:

  /recipeByTitle:
    get:
      summary: Get a recipe by title
      parameters:
        - in: query
          name: title
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipe not found
          content:
            application/json:

        '500':
          description: Internal Server Error
          content:
            application/json:

  /recipeByCount:
    get:
      summary: Get recipes by count
      parameters:
        - in: query
          name: count
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipes not found
          content:
            application/json:

        '500':
          description: Internal Server Error
          content:
            application/json:

  /recipesToDrink/{drink}:
    get:
      summary: Get recipes by drink
      parameters:
        - in: path
          name: drink
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '500':
          description: Internal server error
          content:
            application/json:

  /recipeOfTheDay:
    get:
      summary: Get recipe of the day
      responses:
