/login:
  post:
    summary: Benutzeranmeldung
    description: Authentifiziert den Benutzer und gibt ein JWT-Token zur端ck.
    requestBody:
      required: true
      content:
         application/json:
           schema:
             type: object
             properties:
               userName:
                 type: string
               password:
                 type: string
    responses:
       200:
          description: Erfolgreiche Anmeldung
          content:
            application/json:
              schema:
                type: string
                example: Eingeloggt
       401:
         description: Ung端ltige Anmeldeinformationen
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
                   example: Ung端ltige Anmeldeinformationen
       500:
         description: Serverfehler
         content:
           application/json:
             schema:
               type: object
               properties:
                 error:
                   type: string
                   example: Serverfehler




register:
  post:
    summary: Registrierung eines neuen Benutzers
    description: Registriert einen neuen Benutzer mit den angegebenen Daten.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              firstName:
                type: string
                description: Vorname des Benutzers.
              lastName:
                type: string
                description: Nachname des Benutzers.
              userName:
                type: string
                description: Benutzername des Benutzers.
              emailAddress:
                type: string
                format: email
                description: E-Mail-Adresse des Benutzers.
              password:
                type: string
                format: password
                description: Passwort des Benutzers.
    responses:
      200:
        description: Erfolgreiche Registrierung.
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Erfolgsmeldung.
                user:
                  type: object
                  description: Informationen 端ber den neu registrierten Benutzer.
                  properties:
                    firstName:
                      type: string
                      description: Vorname des Benutzers.
                    lastName:
                      type: string
                      description: Nachname des Benutzers.
                    userName:
                      type: string
                      description: Benutzername des Benutzers.
                    emailAddress:
                      type: string
                      format: email
                      description: E-Mail-Adresse des Benutzers.
      500:
        description: Serverfehler bei der Registrierung.
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                  description: Fehlernachricht.



update/{userId}:
  put:
    summary: Aktualisiert die Daten eines Benutzers
    parameters:
      - in: path
        name: userId
        required: true
        description: Die ID des Benutzers, dessen Daten aktualisiert werden sollen
        schema:
          type: string
      - in: body
        name: updateData
        required: true
        description: Die zu aktualisierenden Daten des Benutzers
        schema:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            userName:
              type: string
            emailAddress:
              type: string
    responses:
      200:
        description: Erfolgreiche Aktualisierung der Benutzerdaten
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string

      404:
        description: Benutzer nicht gefunden
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      500:
        description: Serverfehler
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
